[package]
name = "abc086a"
version = "0.1.0"
authors = ["Ryunosuke Yamada <chihaya9373-adlt@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
